### ISSUE TITLE
Masks for the test datasets are not available

### ISSUE THREAD

**Issue by khc800** [GeorgeBatch/kvasir-seg#4]
Hi, 

I didn't find the masks used for the test dataset. Can you share it? or at least tell me where I can submit the predictions to obtain the scores?

Thanks,

**Comment by GeorgeBatch** [comment]
@khc800, masks for the test set were never released since it was a competition. This GitHub page gives a description: https://github.com/DebeshJha/2020-MediaEval-Medico-polyp-segmentation/tree/master/submission
